### ISSUE TITLE
Scorehud

### ISSUE THREAD

**Issue by PushkarOP** [David-pm-pl/MultiPlayerCounter#6]
Scorehud tag support

**Comment by DavidGlitch04** [comment]
Do you need it to show merged players?

**Comment by PushkarOP** [comment]
Yes

**Comment by DavidGlitch04** [comment]
Dear @PushkarOP,
> Your problem has been accepted.
MPCScoreTag v0.0.1 has fixed this problem please download [it here](https://github.com/David-pm-pl/MPCScoreTag)
